# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CutterPlugin
                                 A QGIS plugin
 Performs an in-place difference operation on the active layer, using the selected feature to clip all overlapping features.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-20
        copyright            : (C) 2025 by Emanuele Gigante
        email                : emanuele.gigante01@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CutterPlugin class from file CutterPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fastcutter import CutterPlugin
    return CutterPlugin(iface)
